# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: openjdk11

dist: xenial
os: linux

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - k-valentin-1989@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="b3e70f72-cd26-4e65-9e3d-0399bcdc09ce"
